### ISSUE TITLE
Review/refactoring meta issue

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#21]
- [x] Review user issues in the forum
- [x] Review the "Refresh" button: perhaps it can happen automatically
- [x] Replace serialize/unserialize by JSON
- [x] Remove deprecated code (`Config::getVar('i18n', 'client_charset')`, `AppLocale`, etc)
- [x] Attempt to use the newer jobs module and get rid of Acron/TaskScheduler checks
- [x] Add auto-formatting for the code
- [x] `include_once('Archive/Tar.php')` not needed (https://github.com/pkp/pln/issues/25)
- [x] Use namespaces
- [x] Use PHP 8 features
- [x] Replace the binary flags by fields: it's complex to view/deal with, better to get it replaced by something simpler (e.g. state machine)
- [x] Remove non-visited code branches
- [x] Attempt to use events to detect modifications on the issues/submissions (useful only if the code which looks for modifications is heavy)
- [x] Review states by checking the ones available in pkppln and locks-o-matic: (https://github.com/pkp/pln/issues/20 + https://github.com/pkp/pln/issues/18)
- [x] Remove non-used locale keys
- [x] Update README with better instructions (how-to images, troubleshooting, etc) and link/reuse the content inside the plugin
- [x] Rename PLN to PN (renaming the folder might be problematic)
- [x] The forum is often orientating users to reset deposits. Sometimes it doesn't make sense, thus this feature should be better controlled.
